sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
before_install:
  - rm yarn.lock
after_script: npm run coveralls
